(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
var notifyyt,notifyqueue;function onYouTubeIframeAPIReady(){notifyyt(),window.loadyt=function(e){e()}}window.loadyt=function(e){var t=document.createElement("script");t.src="https://www.youtube.com/player_api";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n),notifyqueue||(notifyqueue=[],notifyyt=function(){var e;for(e=0;e<notifyqueue.length;++e){(0,notifyqueue[e])()}}),notifyqueue.push(e)};window.plstp||(window.plstp=[]),plst=function(p,w){for(f in window.plstp)window.plstp[f]();window.plstp=[],window.plstp[p]=w},plrm=function(p){delete window.plstp[p]};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1200){var e=document.querySelector('.un96');e.setAttribute('src',(dpi>1)?'images/transparent-logo-326-2.png':'images/transparent-logo-163-2.png');
var e=document.querySelector('.un97');e.setAttribute('src',(dpi>1)?'images/maiarlogowhite-786.jpeg':'images/maiarlogowhite-393.jpeg');
var e=document.querySelector('.un98');e.setAttribute('src',(dpi>1)?'images/google_play-logo.wine-514-1.png':'images/google_play-logo.wine-257-1.png');
var e=document.querySelector('.un99');e.setAttribute('src',(dpi>1)?'images/app-store-emblema-500-1.png':'images/app-store-emblema-250-1.png');
var e=document.querySelector('.un100');e.setAttribute('src',(dpi>1)?'images/huawei_appgallery.svg-336.png':'images/huawei_appgallery.svg-168.png');
var e=document.querySelector('.un101');e.setAttribute('src',(dpi>1)?'images/grayscale-transparent-2078.png':'images/grayscale-transparent-1039.png');}else if($(window).width()>=960){var e=document.querySelector('.un96');e.setAttribute('src',(dpi>1)?'images/transparent-logo-260.png':'images/transparent-logo-130.png');
var e=document.querySelector('.un97');e.setAttribute('src',(dpi>1)?'images/maiarlogowhite-630.jpeg':'images/maiarlogowhite-315.jpeg');
var e=document.querySelector('.un98');e.setAttribute('src',(dpi>1)?'images/google_play-logo.wine-412.png':'images/google_play-logo.wine-206.png');
var e=document.querySelector('.un99');e.setAttribute('src',(dpi>1)?'images/app-store-emblema-400.png':'images/app-store-emblema-200.png');
var e=document.querySelector('.un100');e.setAttribute('src',(dpi>1)?'images/huawei_appgallery.svg-268.png':'images/huawei_appgallery.svg-134.png');
var e=document.querySelector('.un101');e.setAttribute('src',(dpi>1)?'images/grayscale-transparent-1662.png':'images/grayscale-transparent-831.png');}else if($(window).width()>=768){var e=document.querySelector('.un96');e.setAttribute('src',(dpi>1)?'images/transparent-logo-208-1.png':'images/transparent-logo-104.png');
var e=document.querySelector('.un97');e.setAttribute('src',(dpi>1)?'images/maiarlogowhite-502.jpeg':'images/maiarlogowhite-251.jpeg');
var e=document.querySelector('.un98');e.setAttribute('src',(dpi>1)?'images/google_play-logo.wine-330.png':'images/google_play-logo.wine-165.png');
var e=document.querySelector('.un99');e.setAttribute('src',(dpi>1)?'images/app-store-emblema-320.png':'images/app-store-emblema-160.png');
var e=document.querySelector('.un100');e.setAttribute('src',(dpi>1)?'images/huawei_appgallery.svg-214.png':'images/huawei_appgallery.svg-107.png');
var e=document.querySelector('.un101');e.setAttribute('src',(dpi>1)?'images/grayscale-transparent-1330.png':'images/grayscale-transparent-665.png');}else if($(window).width()>=480){var e=document.querySelector('.un96');e.setAttribute('src',(dpi>1)?'images/transparent-logo-198.png':'images/transparent-logo-99.png');
var e=document.querySelector('.un97');e.setAttribute('src',(dpi>1)?'images/maiarlogowhite-488.jpeg':'images/maiarlogowhite-244.jpeg');
var e=document.querySelector('.un98');e.setAttribute('src',(dpi>1)?'images/google_play-logo.wine-544.png':'images/google_play-logo.wine-272.png');
var e=document.querySelector('.un99');e.setAttribute('src',(dpi>1)?'images/app-store-emblema-468-1.png':'images/app-store-emblema-234-1.png');
var e=document.querySelector('.un100');e.setAttribute('src',(dpi>1)?'images/huawei_appgallery.svg-242.png':'images/huawei_appgallery.svg-121.png');
var e=document.querySelector('.un101');e.setAttribute('src',(dpi>1)?'images/grayscale-transparent-950.png':'images/grayscale-transparent-475.png');}else{var e=document.querySelector('.un96');e.setAttribute('src',(dpi>1)?'images/transparent-logo-132.png':'images/transparent-logo-66.png');
var e=document.querySelector('.un97');e.setAttribute('src',(dpi>1)?'images/maiarlogowhite-324.jpeg':'images/maiarlogowhite-162.jpeg');
var e=document.querySelector('.un98');e.setAttribute('src',(dpi>1)?'images/google_play-logo.wine-362.png':'images/google_play-logo.wine-181.png');
var e=document.querySelector('.un99');e.setAttribute('src',(dpi>1)?'images/app-store-emblema-312.png':'images/app-store-emblema-156.png');
var e=document.querySelector('.un100');e.setAttribute('src',(dpi>1)?'images/huawei_appgallery.svg-162.png':'images/huawei_appgallery.svg-81.png');
var e=document.querySelector('.un101');e.setAttribute('src',(dpi>1)?'images/grayscale-transparent-634.png':'images/grayscale-transparent-317.png');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
window.loadyt(function(){var p=new YT.Player('pl1',{host:'https://www.youtube-nocookie.com',videoId: 'PTLV3Bh_abI',playerVars:{'playsinline':1,'rel':0},events:{onStateChange:function(e){1===e.data&&plst('pl1',function(){e.target.pauseVideo()}),2===e.data&&plrm('pl1')}}});});initMenu($('#m1')[0]);
initMenu($('#m2')[0]);
$('.s103').Stickyfill();
if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});